package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const maxLineLength = 100

var (
	showVersion  = flag.Bool("version", false, "Show version and exit")
	filesList    = flag.Bool("files-list", false, "Print included files only")
	graphicTree  = flag.Bool("graphic-tree", false, "Print symbol-formatted tree")
	plainTree    = flag.Bool("plain-tree", false, "Print space-indented tree")
	outputPath   = flag.String("output", "project_doc.txt", "Path to write full documentation output")
	maxSizeBytes = int64(2 * 1024 * 1024) // 2MB

	// Default values if .docgen_ignore doesn't exist
	defaultAlwaysInclude = []string{
		".gitignore",
	}
	defaultAlsoExclude = []string{
		".git/",
		".DS_Store",
	}
)

var version = "dev" // overridden at build time via -ldflags

type Config struct {
	AlwaysInclude []string
	AlsoExclude   []string
}

func main() {
	flag.Parse()

	if *showVersion {
		fmt.Println("docgen version", version)
		return
	}

	root := "."

	config := loadConfig()
	allFiles := collectFiles(root)
	ignored := getIgnoredPaths(allFiles, config.AlsoExclude)
	included := filterIncluded(allFiles, ignored, config.AlwaysInclude)

	switch {
	case *filesList:
		for _, f := range included {
			fmt.Println(f)
		}
	case *graphicTree:
		printTree(included, true)
	case *plainTree:
		printTree(included, false)
	default:
		var buf bytes.Buffer
		buf.WriteString("# DOCGEN-OUTPUT: This file is generated by docgen. Do not include in next generation.\n\n")

		// Usage examples:
		// buf.WriteString(makeHeader("PROJECT FILE TREE:"))
		// buf.WriteString(makeFooter("END OF FILE TREE:"))
		// buf.WriteString(makeHeader("FILE CONTENTS: " + f))
		// buf.WriteString(makeFooter("END OF FILE: " + f))

		buf.WriteString(makeHeader("PROJECT FILE TREE:"))
		buf.WriteString(".\n")
		buf.WriteString(treeString(included, true))
		buf.WriteString(makeFooter("END OF FILE TREE:"))
		buf.WriteString("\n")
		for _, f := range included {
			content, err := os.ReadFile(f)
			if err != nil {
				buf.WriteString(fmt.Sprintf("ERROR reading %s: %v\n\n", f, err))
				continue
			}
			// Double-check for binary content before writing
			if bytes.IndexByte(content, 0) != -1 {
				buf.WriteString(fmt.Sprintf("SKIPPED (binary file): %s\n\n", f))
				continue
			}
			buf.WriteString(makeHeader("FILE CONTENTS: " + f))
			buf.Write(ensureTrailingNewline(content))
			buf.WriteString(makeFooter("END OF FILE: " + f))
			buf.WriteString("\n")
		}
		os.MkdirAll(filepath.Dir(*outputPath), 0755)
		os.WriteFile(*outputPath, buf.Bytes(), 0644)
		fmt.Printf("Documentation written to %s\n", *outputPath)
	}
}

// ensureTrailingNewline ensures content ends with exactly one newline
func ensureTrailingNewline(content []byte) []byte {
	// Remove all trailing newlines
	content = bytes.TrimRight(content, "\n")
	// Add exactly one newline
	return append(content, '\n')
}

// makeHeader creates a header line like: >>>> TEXT >>>>>>>>>>>>>>>>>>>>>>>>>>>>
func makeHeader(text string) string {
	prefix := ">>>> "
	totalPrefix := len(prefix) + len(text) + 1 // +1 for space after text
	repeatCount := maxLineLength - totalPrefix
	if repeatCount < 0 {
		repeatCount = 0
	}
	return fmt.Sprintf("%s%s %s\n", prefix, text, strings.Repeat(">", repeatCount))
}

// makeFooter creates a footer line like: <<<< TEXT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
func makeFooter(text string) string {
	prefix := "<<<< "
	totalPrefix := len(prefix) + len(text) + 1 // +1 for space after text
	repeatCount := maxLineLength - totalPrefix
	if repeatCount < 0 {
		repeatCount = 0
	}
	return fmt.Sprintf("%s%s %s\n", prefix, text, strings.Repeat("<", repeatCount))
}

func loadConfig() Config {
	config := Config{
		AlwaysInclude: defaultAlwaysInclude,
		AlsoExclude:   defaultAlsoExclude,
	}

	file, err := os.Open(".docgen_ignore")
	if err != nil {
		// File doesn't exist, use defaults
		return config
	}
	defer file.Close()

	// Clear defaults since we're reading from file
	config.AlwaysInclude = []string{}
	config.AlsoExclude = []string{}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Lines starting with ! are always included
		if strings.HasPrefix(line, "!") {
			pattern := strings.TrimPrefix(line, "!")
			config.AlwaysInclude = append(config.AlwaysInclude, pattern)
		} else {
			// Everything else is excluded
			config.AlsoExclude = append(config.AlsoExclude, line)
		}
	}

	return config
}

func collectFiles(root string) []string {
	var files []string
	filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		info, err := d.Info()
		if err != nil || info.Size() > maxSizeBytes {
			return nil
		}
		// Skip known binary extensions without reading the file
		if hasKnownBinaryExtension(path) {
			return nil
		}
		// Skip binary files by content inspection
		if isBinaryFile(path) {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files
}

// hasKnownBinaryExtension checks if the file has a common binary extension
func hasKnownBinaryExtension(path string) bool {
	ext := strings.ToLower(filepath.Ext(path))
	binaryExts := []string{
		// Executables
		".exe", ".dll", ".so", ".dylib", ".a", ".o", ".bin",
		// Archives
		".zip", ".tar", ".gz", ".bz2", ".7z", ".rar", ".tgz",
		// Images
		".jpg", ".jpeg", ".png", ".gif", ".bmp", ".ico", ".svg", ".webp",
		// Videos
		".mp4", ".avi", ".mov", ".mkv", ".flv", ".wmv",
		// Audio
		".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a",
		// Documents (binary formats)
		".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
		// Fonts
		".ttf", ".otf", ".woff", ".woff2",
		// Databases
		".db", ".sqlite", ".sqlite3",
		// Other
		".pyc", ".pyo", ".class", ".jar",
	}

	for _, binExt := range binaryExts {
		if ext == binExt {
			return true
		}
	}
	return false
}

// isBinaryFile checks if a file appears to be binary by reading the first chunk of bytes
func isBinaryFile(path string) bool {
	file, err := os.Open(path)
	if err != nil {
		return false
	}
	defer file.Close()

	// Read first 8KB (increased from 512 bytes for better detection)
	buf := make([]byte, 8192)
	n, err := file.Read(buf)
	if n == 0 {
		return false
	}

	// Check for docgen output pragma
	if bytes.HasPrefix(buf[:n], []byte("# DOCGEN-OUTPUT:")) {
		return true // Treat as binary to skip it
	}

	// Check for common binary file signatures (magic bytes)
	if n >= 4 {
		// PDF files start with %PDF
		if bytes.HasPrefix(buf, []byte("%PDF")) {
			return true
		}
		// PNG: 89 50 4E 47
		if bytes.HasPrefix(buf, []byte{0x89, 0x50, 0x4E, 0x47}) {
			return true
		}
		// JPEG: FF D8 FF
		if bytes.HasPrefix(buf, []byte{0xFF, 0xD8, 0xFF}) {
			return true
		}
		// GIF: GIF87a or GIF89a
		if bytes.HasPrefix(buf, []byte("GIF87a")) || bytes.HasPrefix(buf, []byte("GIF89a")) {
			return true
		}
		// ZIP/JAR: 50 4B (PK)
		if bytes.HasPrefix(buf, []byte{0x50, 0x4B}) {
			return true
		}
		// ELF executables: 7F 45 4C 46
		if bytes.HasPrefix(buf, []byte{0x7F, 0x45, 0x4C, 0x46}) {
			return true
		}
		// Mach-O executables (macOS): FE ED FA CE or CE FA ED FE or CF FA ED FE or FE ED FA CF
		if n >= 4 {
			magic := uint32(buf[0])<<24 | uint32(buf[1])<<16 | uint32(buf[2])<<8 | uint32(buf[3])
			if magic == 0xFEEDFACE || magic == 0xCEFAEDFE || magic == 0xCFFAEDFE || magic == 0xFEEDFACF {
				return true
			}
		}
	}

	// Check for null bytes (common in binary files)
	// Also check for high ratio of non-printable characters
	nullCount := 0
	nonPrintable := 0
	for i := 0; i < n; i++ {
		if buf[i] == 0 {
			nullCount++
			if nullCount > 0 {
				return true // Any null byte indicates binary
			}
		}
		// Count non-printable, non-whitespace characters
		if buf[i] < 32 && buf[i] != '\n' && buf[i] != '\r' && buf[i] != '\t' {
			nonPrintable++
		}
	}

	// If more than 30% non-printable characters, likely binary
	if n > 0 && float64(nonPrintable)/float64(n) > 0.3 {
		return true
	}

	return false
}

func getIgnoredPaths(paths []string, alsoExclude []string) map[string]bool {
	ignored := make(map[string]bool)

	// First pass: manually check ALSO_EXCLUDE patterns using gitignore rules
	for _, p := range paths {
		if shouldExclude(p, alsoExclude) {
			ignored[p] = true
		}
	}

	// Second pass: use git check-ignore for .gitignore rules
	// Only check files that weren't already excluded
	var toCheck []string
	for _, p := range paths {
		if !ignored[p] {
			toCheck = append(toCheck, p)
		}
	}

	if len(toCheck) > 0 {
		cmd := exec.Command("git", "check-ignore", "--stdin")
		stdin, _ := cmd.StdinPipe()

		go func() {
			for _, p := range toCheck {
				fmt.Fprintln(stdin, p)
			}
			stdin.Close()
		}()

		output, _ := cmd.Output()
		for _, line := range strings.Split(string(output), "\n") {
			if line != "" {
				ignored[line] = true
			}
		}
	}

	return ignored
}

// shouldExclude checks if a path matches any ALSO_EXCLUDE pattern
// using gitignore-style matching rules
func shouldExclude(path string, patterns []string) bool {
	for _, pattern := range patterns {
		if matchesGitignorePattern(path, pattern) {
			return true
		}
	}
	return false
}

// matchesGitignorePattern implements basic gitignore pattern matching
func matchesGitignorePattern(path, pattern string) bool {
	// Remove leading "./" if present
	path = strings.TrimPrefix(path, "./")

	// Handle directory patterns (ending with /)
	if strings.HasSuffix(pattern, "/") {
		dirPattern := strings.TrimSuffix(pattern, "/")
		// Match if path is in this directory or is the directory itself
		return path == dirPattern || strings.HasPrefix(path, dirPattern+"/")
	}

	// Handle wildcard patterns like *.pyc
	if strings.Contains(pattern, "*") {
		// Match against basename for simple wildcards
		matched, _ := filepath.Match(pattern, filepath.Base(path))
		if matched {
			return true
		}
		// Also try matching the full path for patterns like **/*.pyc
		matched, _ = filepath.Match(pattern, path)
		return matched
	}

	// Exact match or prefix match for simple patterns
	return path == pattern || strings.HasPrefix(path, pattern+"/")
}

func filterIncluded(all []string, ignored map[string]bool, alwaysInclude []string) []string {
	var included []string
	for _, f := range all {
		// Check if file should always be included
		shouldInclude := false
		for _, pattern := range alwaysInclude {
			if matchesGitignorePattern(f, pattern) {
				shouldInclude = true
				break
			}
		}

		// Include if not ignored OR if it's in alwaysInclude
		if shouldInclude || !ignored[f] {
			included = append(included, f)
		}
	}
	sort.Strings(included)
	return included
}

func printTree(paths []string, symbols bool) {
	fmt.Println(".")
	fmt.Print(treeString(paths, symbols))
}

func treeString(paths []string, symbols bool) string {
	tree := make(map[string]interface{})
	for _, path := range paths {
		parts := strings.Split(path, string(os.PathSeparator))
		current := tree
		for i, part := range parts {
			if i == len(parts)-1 {
				current[part] = nil
			} else {
				if _, ok := current[part]; !ok {
					current[part] = make(map[string]interface{})
				}
				current = current[part].(map[string]interface{})
			}
		}
	}
	var buf bytes.Buffer
	renderTree(&buf, tree, "", symbols)
	return buf.String()
}

func renderTree(buf *bytes.Buffer, node map[string]interface{}, prefix string, symbols bool) {
	keys := make([]string, 0, len(node))
	for k := range node {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for i, k := range keys {
		last := i == len(keys)-1
		conn := "├── "
		nextPrefix := prefix + "│   "
		if last {
			conn = "└── "
			nextPrefix = prefix + "    "
		}
		if node[k] == nil {
			if symbols {
				buf.WriteString(fmt.Sprintf("%s%s%s\n", prefix, conn, k))
			} else {
				buf.WriteString(fmt.Sprintf("%s    %s\n", prefix, k))
			}
		} else {
			if symbols {
				buf.WriteString(fmt.Sprintf("%s%s%s/\n", prefix, conn, k))
			} else {
				buf.WriteString(fmt.Sprintf("%s    %s/\n", prefix, k))
			}
			renderTree(buf, node[k].(map[string]interface{}), nextPrefix, symbols)
		}
	}
}
